# Generated by Django 2.2.6 on 2019-10-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
