# Generated by Django 2.1 on 2019-10-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='CustomUser',
            name='birthDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
