# Generated by Django 2.2.6 on 2019-10-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlister', '0004_seed'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeezerSettings',
            fields=[
                ('id', models.SmallIntegerField(editable=False, primary_key=True, serialize=False)),
                ('access_token', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='playlistentry',
            options={'verbose_name': 'Playlist entry', 'verbose_name_plural': 'Playlist entries'},
        ),
    ]
