# Generated by Django 2.2.6 on 2019-10-17 11:16

from django.db import migrations
from django.apps.registry import Apps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def up(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    cls = apps.get_model('playlister', 'DeezerSettings')
    if not cls.objects.exists():
        row = cls()
        row.id = 1
        row.access_token = None
        row.save()


def down(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    cls = apps.get_model('playlister', 'DeezerSettings')
    for o in cls.objects.all():
        o.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('playlister', '0005_add_deezer_settings'),
    ]

    operations = [
        migrations.RunPython(up, down, atomic=True)
    ]
