# Generated by Django 2.2.6 on 2019-10-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlister', '0006_insert_deezer_setting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deezersettings',
            options={'verbose_name': 'Deezer settings', 'verbose_name_plural': 'Deezer settings'},
        ),
        migrations.AddField(
            model_name='deezersettings',
            name='app_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deezersettings',
            name='app_secret',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
